
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app           # Mount your Python code
      - ./pkg:/app/pkg       # Mount WASM artifacts
    working_dir: /app        # Set working directory
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - TRITON_URL=triton:8001
    depends_on:
      - triton

  triton:
    image: nvcr.io/nvidia/tritonserver:22.12-py3
    ports:
      - "8001:8001"
    volumes:
      - ./model_repository:/models
    command: ["tritonserver", "--model-repository=/models"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: